(() => {
  const app = document.getElementById('app');
  const main = document.getElementById('main-content');
  const sidebar = document.getElementById('sidebar');
  const topbar = document.getElementById('topbar');
  const mobileNav = document.getElementById('mobile-nav');
  const dialogMask = document.getElementById('dialog-mask');
  const dialogTitle = document.getElementById('dialog-title');
  const dialogKicker = document.getElementById('dialog-kicker');
  const dialogContent = document.getElementById('dialog-content');
  const dialogConfirm = document.getElementById('dialog-confirm');
  const toast = document.getElementById('toast');
  const store = ZhenkeStore.createStore(ZhenkeSeed, window.localStorage);

  const routes = ['home', 'events', 'event-detail', 'consume', 'mall', 'post-detail', 'author', 'my-posts', 'my-favorites', 'my-likes', 'my-following', 'my-followers', 'my-interactions', 'profile-settings', 'publish', 'topic', 'category', 'merchant-detail', 'service-detail', 'login', 'profile', 'admin-login', 'admin-dashboard', 'admin-merchants', 'admin-services', 'admin-content', 'admin-region', 'admin-audit'];
  const state = { route: 'events', param: '', query: '', cityId: 'handan', section: '土著', admin: null, dialogAction: null, returnAfterLogin: '', publishDraft: null };
  // Mock 相册：纯前端演示没有真实相册，用内置图片模拟“从相册选择”。
  const albumPhotos = [
    { id: 'ph1', src: 'assets/images/city-race.jpg', label: '燃赛现场' },
    { id: 'ph2', src: 'assets/images/ancient-city.jpg', label: '古城风景' },
    { id: 'ph3', src: 'assets/images/dingzhou-food.jpg', label: '本地美食' },
    { id: 'ph4', src: 'assets/images/hotel-room.jpg', label: '住宿体验' },
    { id: 'ph5', src: 'assets/images/night-tour.jpg', label: '古城夜游' }
  ];
  // 可标记的地点（定位）来自现有城市内容地点。
  const publishPlaces = () => (store.getState().services || []).map(item => ({ id: item.id, name: item.name }));
  // 预设话题：发帖时可选，最多 3 个；点击话题进入对应话题的帖子流。
  const presetTopics = ['完赛打卡', '赛前准备', '赛后美食', '古城漫游', '住宿推荐', '本地味道', '亲友团', '第一次跑'];
  const savedAdminId = window.sessionStorage.getItem('zhenkexing-admin-id');
  state.admin = store.getState().admins.find(item => item.id === savedAdminId) || null;
  const userNav = [['events', '燃', '燃'], ['consume', '游', '游'], ['mall', '商', '商'], ['profile', '我', '我']];
  const navIcons = {
    home: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3.5 10.5 8.5-7 8.5 7v9a1.5 1.5 0 0 1-1.5 1.5H5A1.5 1.5 0 0 1 3.5 19.5v-9Z"/><path d="M9 21v-6h6v6"/></svg>',
    consume: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2 1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8L12 2Z"/><path d="m19 16 .8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8L19 16Z"/></svg>',
    mall: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8.5h16l-1 12H5l-1-12Z"/><path d="M8 9V6a4 4 0 0 1 8 0v3"/><path d="M8 13h.01M16 13h.01"/></svg>',
    profile: '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5"/><path d="M5 21a7 7 0 0 1 14 0"/></svg>'
  };
  const adminNav = [
    ['admin-dashboard', '览', '经营看板'], ['admin-merchants', '商', '商家管理'], ['admin-services', '服', '服务管理'], ['admin-content', '文', '内容专题'], ['admin-orders', '单', '订单管理'], ['admin-region', '区', '区域信息'], ['admin-settlement', '账', '分成记录'], ['admin-audit', '志', '操作日志']
  ];
  const categorySymbols = { '餐饮': '宴', '住宿': '宿', '景区': '游', '其他消费': '享' };
  const statusText = { PENDING_PAYMENT: '待支付', PAID: '待使用', CONFIRMED: '已确认', COMPLETED: '已完成', CANCELLED: '已取消', CLOSED: '已关闭', REFUNDED: '已退款', ON_SALE: '已上架', OFF_SALE: '已下架', ACTIVE: '启用', DISABLED: '停用', PUBLISHED: '已发布', DRAFT: '草稿' };
  const money = cents => `¥${(Number(cents || 0) / 100).toFixed(2)}`;
  const safe = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]);
  // 头像可以是相册图片路径，也可以是单个字符。图片路径统一渲染成 <img>。
  const isImageAvatar = value => typeof value === 'string' && /\.(jpg|jpeg|png|webp)$/i.test(value);
  const avatarInner = value => isImageAvatar(value) ? `<img src="${safe(value)}" alt="头像" />` : safe(value || '甄');

  function parseHash() {
    const raw = location.hash.slice(1) || 'events';
    const [route, ...rest] = raw.split('/');
    state.route = routes.includes(route) ? route : 'home';
    state.param = decodeURIComponent(rest.join('/'));
  }
  function go(route, param = '') { location.hash = `${route}${param ? `/${encodeURIComponent(param)}` : ''}`; }
  function isAdminRoute() { return state.route.startsWith('admin-'); }
  function currentHash() { return location.hash.slice(1) || 'events'; }
  // 未登录可自由浏览；发布、关注、点赞、收藏、评论需要登录，登录后按 returnAfterLogin 精确回跳。
  function requireLogin(action) {
    if (store.getState().currentUser) return true;
    state.returnAfterLogin = currentHash();
    showToast('登录后即可' + (action || '互动'));
    go('login');
    return false;
  }
  function pageHeader(kicker, title, description = '', actions = '') { return `<header class="page-header"><div>${kicker ? `<span class="eyebrow">${kicker}</span>` : ''}<h1>${title}</h1>${description ? `<p>${description}</p>` : ''}</div>${actions ? `<div class="header-actions">${actions}</div>` : ''}</header>`; }
  function emptyState(title, body) { return `<section class="empty-state"><span>○</span><h3>${title}</h3><p>${body}</p></section>`; }
  function statusBadge(value) { return `<span class="status-badge status-${String(value).toLowerCase()}">${statusText[value] || value}</span>`; }
  function showToast(message) { toast.textContent = message; toast.classList.add('is-visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('is-visible'), 2200); }
  function openDialog({ kicker = '模拟操作', title, body, confirmText = '确认', onConfirm }) { dialogKicker.textContent = kicker; dialogTitle.textContent = title; dialogContent.innerHTML = body; dialogConfirm.textContent = confirmText; state.dialogAction = onConfirm || null; dialogMask.hidden = false; requestAnimationFrame(() => dialogConfirm.focus()); }
  function closeDialog() { dialogMask.hidden = true; state.dialogAction = null; }

  function renderShell() {
    const admin = isAdminRoute();
    app.classList.toggle('admin-mode', admin);
    app.classList.toggle('home-route', !admin && state.route === 'home');
    app.classList.toggle('consume-route', !admin && state.route === 'consume');
    app.classList.toggle('detail-route', !admin && state.route === 'post-detail');
    document.body.classList.toggle('admin-mode', admin);
    const nav = admin ? adminNav : userNav;
    sidebar.innerHTML = `<a class="brand" href="#${admin ? 'admin-dashboard' : 'home'}"><span class="brand-mark">甄</span><span><strong>定州甄客行</strong><small>${admin ? '运营管理台' : '燃赛文体旅城市社区'}</small></span></a><nav class="side-nav">${nav.map(([route, icon, name]) => `<button class="nav-item ${state.route === route ? 'is-active' : ''}" data-route="${route}"><span>${icon}</span>${name}</button>`).join('')}</nav>${admin ? '<button class="mode-switch" data-route="home">返回用户端</button>' : '<button class="mode-switch" data-route="admin-login">进入运营后台</button>'}`;
    const showSearch = !admin && state.route === 'consume';
    topbar.innerHTML = admin ? `<div class="topbar-title"><b>定州区域</b><small>${state.admin ? state.admin.name : '运营管理员演示'}</small></div>` : `<button class="mobile-brand" data-route="events"><b class="mobile-brand-title">甄客行</b><small>燃赛文体旅城市社区</small></button>${showSearch ? `<label class="global-search"><span>⌕</span><input type="search" value="${safe(state.query)}" placeholder="搜索燃赛故事、地点和帖子" data-search /></label>` : ''}`;
    mobileNav.innerHTML = nav.map(([route, icon, name]) => `<button class="mobile-nav-item ${state.route === route ? 'is-active' : ''}" data-route="${route}"><span>${admin ? icon : (navIcons[route] || icon)}</span><small>${name}</small></button>`).join('');
  }

  function serviceCard(service) {
    const merchant = store.getMerchant(service.merchantId);
    const available = store.canPurchase(service.id);
    const sliked = store.isServiceLiked(service.id); const sfav = store.isServiceFavorited(service.id);
    return `<article class="service-card"><button class="service-cover" data-route="service-detail" data-param="${service.id}" aria-label="查看${safe(service.name)}">${service.image ? `<img src="${safe(service.image)}" alt="${safe(service.name)}" loading="lazy" />` : `<span>${safe(service.symbol)}</span>`}</button><div class="service-copy"><span class="merchant-line">${safe(merchant?.name)}</span><h3>${safe(service.name)}</h3><p>${safe(service.description)}</p><div class="event-tags">${(service.eventTags || []).map(tag => `<span>${safe(tag)}</span>`).join('')}</div><div class="service-actions"><button class="post-action ${sliked ? 'is-active' : ''}" data-service-like="${service.id}"><span>${sliked ? '♥' : '♡'}</span>${store.serviceLikeCount(service.id)}</button><button class="post-action ${sfav ? 'is-active' : ''}" data-service-favorite="${service.id}"><span>${sfav ? '★' : '☆'}</span>${store.serviceFavoriteCount(service.id)}</button><button class="post-action" data-route="service-detail" data-param="${service.id}"><span>💬</span>${store.servicePostCount(service.id)}</button></div></div></article>`;
  }
  function merchantCard(merchant) { return `<article class="merchant-card"><div class="merchant-symbol">${merchant.symbol}</div><div><span class="eyebrow">${merchant.category}</span><h3>${safe(merchant.name)}</h3><p>${safe(merchant.address)}</p><button class="text-button" data-route="merchant-detail" data-param="${merchant.id}">查看商家与服务 →</button></div></article>`; }
  function reviewServiceId(review) { if (review.serviceId) return review.serviceId; if (review.source?.includes('古城文化讲解')) return 'SV003'; if (review.source?.includes('中山宴')) return 'SV002'; if (review.source?.includes('国际酒店')) return 'SV001'; return ''; }
  function reviewImage(review) { const id = reviewServiceId(review); return id === 'SV001' ? 'assets/images/hotel-room.jpg' : id === 'SV002' ? 'assets/images/dingzhou-food.jpg' : id === 'SV003' ? 'assets/images/ancient-city.jpg' : 'assets/images/city-race.jpg'; }
  function reviewCard(review) { const serviceId = reviewServiceId(review); const service = serviceId ? store.getService(serviceId) : null; return `<article class="review-card"><img class="review-image" src="${reviewImage(review)}" alt="${safe(review.source || '甄客帖体验')}" loading="lazy" /><p class="review-text">${safe(review.text)}</p>${serviceId ? `<button class="review-product-link" data-route="service-detail" data-param="${serviceId}"><img class="review-product-image" src="${safe(service?.image || reviewImage(review))}" alt="${safe(service?.name || '查看商品')}" /><span class="review-product-name">${safe(service?.name || '查看商品')}</span><span class="review-product-arrow">→</span></button>` : ''}<footer><span class="review-author"><span class="review-avatar">${safe(review.avatar)}</span><b>${safe(review.user)}</b></span><button class="review-like" data-like="${review.id}">♥ ${review.likes}</button></footer></article>`; }
  function orderSchedule(order) { if (order.category === '住宿' && order.endDate) return `入住 ${order.useDate} · 离店 ${order.endDate}`; if (order.category === '餐饮') return '团购套餐 · 到店核销'; if (order.category === '景区' && order.visitSlot) return `${order.useDate} · ${order.visitSlot}`; return `使用日期 ${order.useDate}`; }
  function orderCard(order, admin = false) { return `<article class="order-card"><header><span>${safe(order.merchantName)}</span>${statusBadge(order.status)}</header><div class="order-main"><span class="order-symbol">${categorySymbols[order.category] || '享'}</span><div><h3>${safe(order.serviceName)}</h3><p>订单号 ${order.id} · ${safe(orderSchedule(order))}</p></div><strong>${money(order.amount)}</strong></div><footer><button class="secondary-button small-button" data-route="${admin ? 'admin-order-detail' : 'order-detail'}" data-param="${order.id}">查看详情</button>${!admin && order.status === 'PENDING_PAYMENT' ? `<button class="primary-button small-button" data-route="payment" data-param="${order.id}">继续支付</button>` : ''}</footer></article>`; }

  function renderHome() {
    const data = store.getState();
    const event = data.events.find(item => item.status === 'PUBLISHED');
    const topEnjoy = data.services.filter(item => ['餐饮', '住宿', '景区'].includes(item.category)).sort((a, b) => (b.popularity || 0) - (a.popularity || 0)).slice(0, 4);
    const enjoyLabel = { '餐饮': '必吃', '住宿': '必住', '景区': '必玩' };
    return `<section class="section home-first"><div class="section-heading"><div><span class="eyebrow">CITY × EVENT</span><h1>燃赛定州</h1></div><button class="text-button" data-route="events">全部赛事 →</button></div><div class="city-carousel"><article class="city-banner city-event-banner tone-race"><img src="assets/images/city-race.jpg" alt="城市路跑赛事" /><span class="event-countdown">距开赛还有 8 天</span><span>${event.date} · ${event.place}</span><h2>${safe(event.title)}</h2><p>${safe(event.intro)}</p><div class="hero-actions"><button class="primary-button" data-route="event-detail" data-param="${event.id}">进入赛事专题</button></div></article>${data.cityBanners.filter(item => item.targetId !== event.id).map(item => `<button class="city-banner tone-${item.tone}" data-route="${item.targetRoute}" ${item.targetId ? `data-param="${item.targetId}"` : ''}>${item.image ? `<img src="${safe(item.image)}" alt="${safe(item.title)}" loading="lazy" />` : ''}<span>定州 · 城市推荐</span><h2>${safe(item.title)}</h2><p>${safe(item.subtitle)}</p><b>探索更多 →</b></button>`).join('')}</div></section>
    <section class="section"><div class="section-heading"><div><span class="eyebrow">TRAVEL PLAN</span><h2>一日游 · 两日游 · 多日游</h2></div></div><div class="package-track">${data.travelPackages.map(item => `<article class="package-card"><span>${safe(item.stage)}</span><h3>${safe(item.title)}</h3><p>${item.items.map(safe).join(' · ')}</p><footer><strong>${money(item.price)} 起</strong><button class="small-button primary-button" data-route="consume">查看套餐</button></footer></article>`).join('')}</div></section>
    <section class="section zhen-enjoy"><div class="section-heading"><div><span class="eyebrow">ZHEN PICKS</span><h2>甄必享</h2></div><button class="text-button" data-route="consume">查看全部 →</button></div><div class="zhen-enjoy-track">${topEnjoy.map(service => { const merchant = store.getMerchant(service.merchantId); return `<article class="zhen-pick-card"><button class="zhen-pick-cover" data-route="service-detail" data-param="${service.id}">${service.image ? `<img src="${safe(service.image)}" alt="${safe(service.name)}" loading="lazy" />` : `<span>${safe(service.symbol)}</span>`}<b>${enjoyLabel[service.category]}</b></button><div><small>${safe(merchant?.name)} · 热度 ${service.popularity || 80}</small><h3>${safe(service.name)}</h3><footer><strong>${money(service.price)}</strong><button class="text-button" data-route="service-detail" data-param="${service.id}">查看 →</button></footer></div></article>`; }).join('')}</div></section>
    <section class="section"><div class="section-heading"><div><span class="eyebrow">VERIFIED EXPERIENCE</span><h2>精选甄客帖</h2></div><button class="text-button" data-route="reviews">查看全部 →</button></div><div class="review-list wide">${data.reviews.slice(0, 2).map(reviewCard).join('')}</div></section>`;
  }
  function renderEvents() { const events = store.getState().events; return `${pageHeader('EVENTS', '赛事专题', '赛事报名复用燃赛能力，甄客行提供周边消费服务。')}<div class="event-list">${events.map(event => `<article class="event-card"><div class="event-stamp">赛</div><div><div class="tag-row">${statusBadge(event.status)}<span>${event.date}</span></div><h2>${safe(event.title)}</h2><p>${safe(event.place)} · ${safe(event.cover)}</p><button class="primary-button" data-route="event-detail" data-param="${event.id}">查看专题</button></div></article>`).join('')}</div>`; }
  function renderEventDetail() { const event = store.getEvent(state.param || 'E001'); if (!event) return emptyState('赛事不存在', '请返回赛事列表。'); const services = event.relatedServiceIds.map(store.getService).filter(Boolean); return `${pageHeader('EVENT DETAIL', event.title, `${event.date} · ${event.place}`, '<button class="primary-button" data-ransai>前往燃赛报名</button>')}<section class="detail-hero"><div class="detail-symbol">赛</div><div><h2>赛事介绍</h2><p>${safe(event.intro)}</p><div class="info-strip"><span><b>交通</b> 定州东站赛事接驳</span><span><b>服务</b> 住宿、餐饮、景区</span></div></div></section><section class="section"><div class="section-heading"><div><h2>赛事关联服务</h2></div></div><div class="service-grid">${services.map(serviceCard).join('')}</div></section>`; }
  function renderConsume() { const data = store.getState(); const labels = [['甄必享', ''], ['美食', '餐饮'], ['酒店', '住宿'], ['景区', '景区']]; const selected = state.param || ''; const services = data.services.filter(item => (!selected || item.category === selected) && (!state.query || JSON.stringify(item).includes(state.query))).sort((a, b) => (b.popularity || 0) - (a.popularity || 0)); return `<div class="filter-row">${labels.map(([label, value]) => `<button class="filter-button ${selected === value ? 'is-active' : ''}" data-route="consume" data-param="${value}">${label}</button>`).join('')}</div><section class="section"><div class="section-heading"><div><h2>${state.query ? `搜索“${safe(state.query)}”` : (selected ? labels.find(item => item[1] === selected)?.[0] : '甄必享')}</h2></div></div><div class="service-grid">${services.length ? services.map(serviceCard).join('') : emptyState('没有找到相关服务', '换个关键词试试。')}</div></section>`; }
  function renderCategory() { const category = state.param || '餐饮'; const data = store.getState(); const merchants = data.merchants.filter(item => item.category === category); const services = data.services.filter(item => item.category === category && JSON.stringify(item).includes(state.query)); return `${pageHeader('CATEGORY', category, '', '<button class="secondary-button" data-route="consume">返回分类</button>')}<section class="section"><div class="section-heading"><div><h2>本地商家</h2></div></div><div class="merchant-grid">${merchants.map(merchantCard).join('')}</div></section><section class="section"><div class="section-heading"><div><h2>可选服务</h2></div></div><div class="service-grid">${services.length ? services.map(serviceCard).join('') : emptyState('没有匹配服务', '请更换搜索词。')}</div></section>`; }
  function renderMerchantDetail() { const merchant = store.getMerchant(state.param); if (!merchant) return emptyState('商家不存在', '请返回消费分类。'); const services = store.getState().services.filter(item => item.merchantId === merchant.id); return `${pageHeader('MERCHANT', merchant.name, `${merchant.category} · ${statusText[merchant.status]}`, '<button class="secondary-button" data-route="consume">返回消费</button>')}<section class="detail-hero"><div class="detail-symbol">${merchant.symbol}</div><div><h2>商家信息</h2><p>${safe(merchant.intro)}</p><div class="definition-grid"><span><b>地址</b>${safe(merchant.address)}</span><span><b>电话</b>${safe(merchant.phone)}</span><span><b>营业时间</b>${safe(merchant.hours)}</span><span><b>服务须知</b>实际履约信息以上线数据为准</span></div></div></section><section class="section"><h2>在售服务</h2><div class="service-grid">${services.map(serviceCard).join('')}</div></section>`; }
  function renderServiceDetail() { const service = store.getService(state.param); if (!service) return emptyState('服务不存在', '请返回享。'); const data = store.getState(); const merchant = store.getMerchant(service.merchantId); const availability = store.canPurchase(service.id); const reviews = data.reviews.filter(item => item.category === service.category); const comments = (data.comments || []).filter(item => item.serviceId === service.id); return `${pageHeader('CITY SERVICE', service.name, `${service.category} · ${merchant.name}`, '<button class="secondary-button" data-route="consume">返回“享”</button>')}<section class="detail-gallery"><div>${service.symbol}</div><div>${service.symbol}</div><div>${service.symbol}</div></section><section class="service-detail"><div class="service-detail-copy"><div class="tag-row">${statusBadge(service.status)}<span>热度 ${service.popularity || 80}</span><span>${safe(merchant.address)}</span></div><h2>${money(service.price)}</h2><div class="event-tags">${(service.eventTags || []).map(tag => `<span>${safe(tag)}</span>`).join('')}</div><h3>商家与服务介绍</h3><p>${safe(merchant.intro)} ${safe(service.description)}</p><div class="notice-box event-service-box"><b>赛事配套服务</b><p>${safe(service.eventService || '适合参赛者、观赛亲友团和城市游客。')}</p></div><h3>套餐与购买内容</h3><div class="definition-grid"><span><b>库存</b>${service.stock}</span><span><b>有效期</b>${service.validUntil}</span><span><b>履约方式</b>${service.fulfillmentType === 'VERIFY_AT_STORE' ? '到店出示核销码' : '运营管理员预约确认'}</span><span><b>购买须知</b>${safe(service.notice)}</span></div></div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">VERIFIED</span><h2>甄客帖</h2><p>只有已购买、已核销或完成履约的消费者可以发布。</p></div></div><div class="review-list wide">${reviews.length ? reviews.map(reviewCard).join('') : emptyState('暂无甄客帖', '完成购买和履约后可发布真实评价。')}</div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">DISCUSSION</span><h2>评论区</h2><p>普通用户可提问、讨论和查看商家回复，不代表已经购买。</p></div></div><div class="comment-list">${comments.length ? comments.map(item => `<article class="comment-card"><strong>${safe(item.user)}</strong><span>普通评论 · 未验证购买</span><p>${safe(item.text)}</p><div><b>回复</b>${safe(item.reply)}</div></article>`).join('') : emptyState('暂无评论', '登录后可以提问。')}</div><button class="secondary-button" data-demo-comment>我要提问</button></section><div class="purchase-bar"><div><small>${merchant.name}</small><strong>${money(service.price)}</strong></div><button class="primary-button" ${availability.ok ? `data-buy="${service.id}"` : 'disabled'}>${availability.ok ? '立即购买' : availability.reason}</button></div>`; }
  function renderLogin() { return `<section class="login-page"><div class="login-brand"><span class="brand-mark">甄</span><h1>登录 / 注册</h1><p>手机号验证登录，未注册将自动创建账号</p></div><form class="form-card login-form" data-user-login><label>手机号<input name="phone" inputmode="tel" maxlength="11" required pattern="1[0-9]{10}" placeholder="请输入手机号" /></label><label>验证码<span class="code-field"><input name="code" inputmode="numeric" maxlength="6" required placeholder="6 位验证码" /><button type="button" class="code-button" data-send-code>获取验证码</button></span></label><label class="agreement"><input type="checkbox" name="agree" required /> 我已阅读并同意《用户协议》和《隐私政策》</label><button class="primary-button block-button" type="submit">登录</button></form></section>`; }
  function renderCheckout() { const service = store.getService(state.param || state.pendingServiceId); if (!service) return emptyState('没有待确认服务', '请先选择一项服务。'); const merchant = store.getMerchant(service.merchantId); const booking = service.category === '住宿' ? `<label>入住日期<input name="checkInDate" type="date" value="2026-09-01" required /></label><label>离店日期<input name="checkOutDate" type="date" value="2026-09-02" required /></label><label>房间数<input name="quantity" type="number" value="1" min="1" max="5" required /></label><label>入住人<input name="guestName" value="甄客用户" required /></label>` : service.category === '景区' ? `<label>入园日期<input name="visitDate" type="date" value="2026-09-01" required /></label><label>入园场次<select name="visitSlot" required><option>09:00–12:00</option><option>13:00–17:00</option><option>夜游场次</option></select></label><label>票数<input name="quantity" type="number" value="1" min="1" max="8" required /></label><label>游客联系人<input name="guestName" value="甄客用户" required /></label>` : service.category === '餐饮' ? `<div class="package-choice"><b>团购套餐</b><p>${safe(service.description)}</p><span>购买后到店出示核销码验券</span></div><label>套餐数量<input name="quantity" type="number" value="1" min="1" max="12" required /></label>` : `<label>预约日期<input name="useDate" type="date" value="2026-09-01" required /></label><label>数量<input name="quantity" type="number" value="1" min="1" max="5" required /></label>`; return `${pageHeader('ORDER CONFIRMATION', '确认订单')}<form class="checkout-layout booking-type booking-${service.category}" data-checkout data-service-id="${service.id}"><section class="form-card"><div class="booking-progress"><b>${service.category === '餐饮' ? '1 选择团购套餐' : '1 选择服务日期'}</b><span>2 填写联系人</span><span>3 提交订单</span></div><h2>${service.category === '住宿' ? '住宿信息' : service.category === '景区' ? '游玩信息' : service.category === '餐饮' ? '团购套餐' : '预约信息'}</h2>${booking}<label>联系人手机号<input name="contactPhone" value="13800000000" required pattern="1[0-9]{10}" /></label><label>备注<textarea name="note" placeholder="选填"></textarea></label></section><aside class="summary-card"><span>${merchant.name}</span><h2>${service.name}</h2><p>${service.description}</p><div class="summary-line"><span>单价</span><strong>${money(service.price)}</strong></div><div class="summary-line"><span>数量</span><strong data-quantity-label>按选择计算</strong></div><div class="summary-line"><span>应付金额</span><strong>${money(service.price)}</strong></div><label class="agreement"><input type="checkbox" required /> 我已阅读服务协议</label><button class="primary-button block-button" type="submit">提交订单并支付</button></aside></form>`; }
  function renderPayment() { const order = store.getOrder(state.param); if (!order) return emptyState('订单不存在', '请返回订单列表。'); return `${pageHeader('MOCK PAYMENT', '选择模拟支付结果', '请选择支付结果。')}<section class="payment-card"><div class="payment-amount"><span>应付金额</span><strong>${money(order.amount)}</strong><small>订单号 ${order.id}</small></div><div class="payment-options"><button data-pay="SUCCESS"><span>✓</span><b>模拟支付成功</b><small>进入待使用并生成核销码</small></button><button data-pay="PROCESSING"><span>…</span><b>模拟支付处理中</b><small>在订单列表等待结果</small></button><button data-pay="FAILED"><span>×</span><b>模拟支付失败</b><small>保留订单并允许重新支付</small></button></div></section>`; }
  function renderPaymentResult() { const order = store.getOrder(state.param); if (!order) return emptyState('订单不存在', '请返回订单列表。'); const map = { SUCCESS: ['支付成功', '订单已进入待使用状态。'], PROCESSING: ['支付处理中', '可稍后在订单列表查看最终结果。'], FAILED: ['支付失败', '未发生真实扣款，可以重新模拟支付。'] }; const result = map[order.paymentStatus] || ['待支付', '当前订单尚未支付。']; return `<section class="result-card result-${order.paymentStatus.toLowerCase()}"><span>${order.paymentStatus === 'SUCCESS' ? '✓' : order.paymentStatus === 'FAILED' ? '×' : '…'}</span><h1>${result[0]}</h1><p>${result[1]}</p><strong>${money(order.amount)}</strong><div><button class="primary-button" data-route="order-detail" data-param="${order.id}">查看订单</button>${order.paymentStatus === 'FAILED' ? `<button class="secondary-button" data-route="payment" data-param="${order.id}">重新支付</button>` : ''}</div></section>`; }
  function renderOrders() { const map = { '全部': '', '待支付': 'PENDING_PAYMENT', '待使用': 'PAID', '已完成': 'COMPLETED', '已取消/关闭': 'CANCELLED' }; const orders = store.listOrders({ status: map[state.orderFilter] }); return `${pageHeader('MY ORDERS', '我的订单', '查看支付、预约和核销状态。')}<div class="filter-row">${Object.keys(map).map(label => `<button class="filter-button ${state.orderFilter === label ? 'is-active' : ''}" data-order-filter="${label}">${label}</button>`).join('')}</div><div class="order-list">${orders.length ? orders.map(order => orderCard(order)).join('') : emptyState('没有相关订单', '尝试切换订单状态。')}</div>`; }
  function renderOrderDetail() { const order = store.getOrder(state.param); if (!order) return emptyState('订单不存在', '请返回订单列表。'); return `${pageHeader('ORDER DETAIL', '订单详情', order.id, '<button class="secondary-button" data-route="orders">返回订单</button>')}<section class="order-detail-grid"><div class="form-card"><div class="detail-row"><span>订单状态</span>${statusBadge(order.status)}</div><div class="detail-row"><span>服务</span><b>${safe(order.serviceName)}</b></div><div class="detail-row"><span>商家</span><b>${safe(order.merchantName)}</b></div><div class="detail-row"><span>联系人</span><b>${safe(order.contactName)} · ${safe(order.contactPhone)}</b></div><div class="detail-row"><span>${order.category === '住宿' ? '入住安排' : order.category === '景区' ? '入园安排' : order.category === '餐饮' ? '核销方式' : '预约安排'}</span><b>${safe(orderSchedule(order))}</b></div><div class="detail-row"><span>支付状态</span><b>${safe(order.paymentStatus)}</b></div><div class="detail-row"><span>订单金额</span><b>${money(order.amount)}</b></div></div><aside class="verification-card ${order.verificationCode && order.paymentStatus === 'SUCCESS' ? '' : 'is-disabled'}"><span>核销凭证</span>${order.verificationCode && order.paymentStatus === 'SUCCESS' ? `<div class="qr-mock">${order.verificationCode.slice(-4)}</div><strong>${order.verificationCode}</strong><p>到店向运营管理员出示此模拟核销码</p>` : '<h2>暂未生成</h2><p>支付成功后才会生成核销码。</p>'}</aside></section>`; }
  function renderReviews() { const data = store.getState(); const categories = ['全部', '餐饮', '住宿', '景区']; const items = data.reviews.filter(item => state.reviewCategory === '全部' || item.category === state.reviewCategory); return `${pageHeader('VERIFIED EXPERIENCE', '甄客帖', '保留用户真实履约后的体验内容展示；当前均为模拟数据。')}<div class="filter-row">${categories.map(category => `<button class="filter-button ${state.reviewCategory === category ? 'is-active' : ''}" data-review-filter="${category}">${category}</button>`).join('')}</div><div class="review-list wide">${items.map(reviewCard).join('')}</div>`; }
  function renderProfile() { const user = store.getState().currentUser; return `<section class="profile-grid profile-page"><div class="profile-card profile-hero"><button class="profile-avatar" data-change-avatar aria-label="更换头像">${safe(user?.avatar || '甄')}<span class="avatar-edit-mark">✎</span></button><div class="profile-hero-copy"><h2>${safe(user?.name || '未登录用户')}</h2><p>${user?.phone ? user.phone.replace(/(\d{3})\d{4}(\d{4})/, '$1****$2') : '尚未登录'}</p><small>甄客用户</small></div></div><div class="entry-grid profile-actions"><button data-route="orders"><h3>我的订单</h3><p>查看订单状态</p></button><button data-route="reviews"><h3>我的甄客帖</h3><p>查看真实履约评价</p></button><button data-route="profile-settings"><h3>编辑资料</h3><p>修改昵称和手机号</p></button></div></section>`; }
  function renderProfileSettings() {
    if (!store.getState().currentUser) { go('login'); return ''; }
    const me = userById('U001');
    return `${pageHeader('ACCOUNT SETTINGS', '编辑资料', '', '<button class="secondary-button" data-route="profile">返回我的</button>')}<form class="form-card profile-settings-form" data-profile-settings><button type="button" class="settings-avatar" data-change-avatar aria-label="更换头像"><span class="settings-avatar-inner">${avatarInner(me.avatar)}</span><small>点击更换头像</small></button><label>昵称<input name="name" value="${safe(me.nickname)}" required maxlength="20" placeholder="填写昵称" /></label><label>简介<textarea name="bio" maxlength="60" placeholder="一句话介绍自己">${safe(me.bio)}</textarea></label><button class="primary-button block-button" type="submit">保存资料</button></form><button class="text-button danger-text block-button" data-logout>退出登录</button>`;
  }
  function renderMall() { return `<section class="coming-soon"><span>◫</span><h1>商城暂未开放</h1><p>商城将通过统一接口接入，敬请期待。</p><div><button class="primary-button" data-route="home">返回首页</button><button class="secondary-button" data-route="consume">去“游”看看</button></div></section>`; }

  function requireAdmin() { if (!state.admin) { go('admin-login'); return false; } return true; }
  function renderAdminLogin() { return `<section class="admin-login-card"><div><span class="eyebrow">OPERATOR CONSOLE · MOCK</span><h1>定州运营管理台</h1><p>首轮只设置运营管理员负责区域运营；平台管理员作为未来跨区域能力预留。</p></div><form data-admin-login><label>演示账号<input name="account" value="dingzhou-admin" required /></label><label>演示密码<input type="password" value="123456" required /></label><button class="primary-button block-button" type="submit">登录模拟后台</button><small>不会进行真实身份验证</small></form></section>`; }
  function renderAdminDashboard() { if (!requireAdmin()) return ''; const data = store.getState(); const paid = data.orders.filter(item => ['PAID', 'CONFIRMED', 'COMPLETED'].includes(item.status)); const total = paid.reduce((sum, item) => sum + item.amount, 0); return `${pageHeader('DASHBOARD', '经营数据看板', '所有指标均为模拟数据，统计口径为当前定州区域。')}<section class="metric-grid"><div><span>今日订单</span><strong>${data.orders.length}</strong><small>笔</small></div><div><span>累计成交</span><strong>${money(total)}</strong><small>已支付订单</small></div><div><span>待核销</span><strong>${data.orders.filter(item => item.status === 'PAID').length}</strong><small>笔</small></div><div><span>退款金额</span><strong>${money(data.orders.filter(item => item.status === 'REFUNDED').reduce((s, i) => s + i.amount, 0))}</strong><small>模拟</small></div></section><section class="admin-grid"><div class="admin-panel"><h2>订单状态分布</h2>${['PENDING_PAYMENT', 'PAID', 'CONFIRMED', 'COMPLETED', 'CANCELLED'].map(status => `<div class="progress-row"><span>${statusText[status]}</span><i><b style="width:${Math.max(8, data.orders.filter(item => item.status === status).length / data.orders.length * 100)}%"></b></i><strong>${data.orders.filter(item => item.status === status).length}</strong></div>`).join('')}</div><div class="admin-panel"><h2>分类成交金额</h2>${['餐饮', '住宿', '景区', '其他消费'].map(category => `<div class="detail-row"><span>${category}</span><b>${money(paid.filter(item => item.category === category).reduce((s, i) => s + i.amount, 0))}</b></div>`).join('')}</div></section>`; }
  function adminTable(headers, rows) { return `<div class="table-wrap"><table><thead><tr>${headers.map(item => `<th>${item}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`; }
  function renderAdminMerchants() { if (!requireAdmin()) return ''; const rows = store.getState().merchants.map(item => `<tr><td><b>${safe(item.name)}</b><small>${safe(item.address)}</small></td><td>${item.category}</td><td>${statusBadge(item.status)}</td><td>${store.getState().services.filter(service => service.merchantId === item.id).length}</td><td><button class="secondary-button small-button" data-toggle-merchant="${item.id}">${item.status === 'ACTIVE' ? '停用' : '启用'}</button></td></tr>`); return `${pageHeader('MERCHANTS', '商家管理', '管理定州区域商家；商城商家不在本后台维护。','<button class="primary-button" data-demo-add="merchant">新增商家</button>')}${adminTable(['商家', '分类', '状态', '服务数', '操作'], rows)}`; }
  function renderAdminServices() { if (!requireAdmin()) return ''; const rows = store.getState().services.map(item => `<tr><td><b>${safe(item.name)}</b><small>${safe(store.getMerchant(item.merchantId)?.name)}</small></td><td>${item.category}</td><td>${money(item.price)}</td><td>${item.stock}</td><td>${statusBadge(item.status)}</td><td><button class="secondary-button small-button" data-toggle-service="${item.id}">${item.status === 'ON_SALE' ? '下架' : '上架'}</button></td></tr>`); return `${pageHeader('SERVICES', '商品/服务管理', '首轮管理赛事消费服务，不包含既有商城商品。','<button class="primary-button" data-demo-add="service">新增服务</button>')}${adminTable(['服务', '分类', '价格', '库存', '状态', '操作'], rows)}`; }
  function renderAdminContent() { if (!requireAdmin()) return ''; const data = store.getState(); return `${pageHeader('CONTENT', '内容与赛事专题', '维护首页轮播、推荐位和赛事专题状态。','<button class="primary-button" data-demo-add="content">新增内容</button>')}<div class="admin-card-grid">${data.contents.map(item => `<article class="admin-card"><span>${item.type}</span><h3>${item.title}</h3><p>${item.subtitle}</p>${statusBadge(item.status)}<button class="secondary-button small-button" data-toggle-content="${item.id}">${item.status === 'PUBLISHED' ? '转为草稿' : '发布'}</button></article>`).join('')}${data.events.map(item => `<article class="admin-card"><span>EVENT</span><h3>${item.title}</h3><p>${item.date} · ${item.place}</p>${statusBadge(item.status)}<button class="secondary-button small-button" data-demo-edit="${item.id}">编辑专题</button></article>`).join('')}</div>`; }
  function renderAdminOrders() { if (!requireAdmin()) return ''; const orders = store.getState().orders.filter(item => !state.query || JSON.stringify(item).includes(state.query)); return `${pageHeader('ORDERS', '订单管理', '按订单号、手机号、商家和状态查询模拟订单。')}<div class="order-list">${orders.map(order => orderCard(order, true)).join('')}</div>`; }
  function renderAdminOrderDetail() { if (!requireAdmin()) return ''; const order = store.getOrder(state.param); if (!order) return emptyState('订单不存在', '返回订单管理。'); return `${pageHeader('ORDER OPERATION', '订单处理', order.id, '<button class="secondary-button" data-route="admin-orders">返回订单</button>')}<section class="order-detail-grid"><div class="form-card">${[['状态', statusText[order.status]], ['服务', order.serviceName], ['商家', order.merchantName], ['联系人', `${order.contactName} · ${order.contactPhone}`], ['使用日期', order.useDate], ['支付状态', order.paymentStatus], ['金额', money(order.amount)]].map(([k, v]) => `<div class="detail-row"><span>${k}</span><b>${safe(v)}</b></div>`).join('')}<div class="admin-actions">${['PAID', 'CONFIRMED'].includes(order.status) ? `<button class="primary-button" data-admin-order-action="VERIFY" data-id="${order.id}">核销完成</button>` : ''}${order.status === 'PAID' ? `<button class="secondary-button" data-admin-order-action="CONFIRM" data-id="${order.id}">预约确认</button>` : ''}${!['COMPLETED', 'CANCELLED', 'REFUNDED'].includes(order.status) ? `<button class="danger-button" data-admin-order-action="REFUND" data-id="${order.id}">登记退款</button>` : ''}</div></div><aside class="verification-card"><span>核销码</span><strong>${order.verificationCode || '未生成'}</strong><p>管理操作会同步更新用户端并写入审计日志。</p></aside></section>`; }
  function renderAdminRegion() { if (!requireAdmin()) return ''; const region = store.getState().region; return `${pageHeader('REGION', '区域与运营主体', '首期固定定州，数据结构保留多区域扩展能力。')}<section class="form-card"><div class="detail-row"><span>区域编码</span><b>${region.code}</b></div><div class="detail-row"><span>区域名称</span><b>${region.name}</b></div><div class="detail-row"><span>运营主体</span><b>${region.operatorName}</b></div><div class="detail-row"><span>联系电话</span><b>${region.contact}</b></div><div class="detail-row"><span>运营角色</span><b>运营管理员</b></div><div class="notice-box"><b>平台管理员</b><p>未来可跨区域查看和管理；首轮不制作重复后台。</p></div></section>`; }
  function renderAdminSettlement() { if (!requireAdmin()) return ''; const orders = store.getState().orders.filter(item => item.settlement); const rows = orders.map(item => `<tr><td>${item.id}</td><td>${money(item.amount)}</td><td>${money(item.settlement.platformFee)}</td><td>${money(item.settlement.operatorShare)}</td><td>${money(item.settlement.merchantAmount)}</td><td>${item.settlement.ruleVersion}</td></tr>`); return `${pageHeader('SETTLEMENT', '交易费与分成记录', '仅展示订单分成快照，不执行自动结算或打款。')}${adminTable(['订单号', '成交金额', '平台服务费', '运营方分成', '商家应结算', '规则'], rows)}`; }
  function renderAdminAudit() { if (!requireAdmin()) return ''; const rows = store.getState().auditLogs.map(item => `<tr><td>${item.time}</td><td>${safe(item.actorName)}</td><td>${safe(item.resource)}</td><td>${safe(item.action)}</td><td>${safe(item.summary)}</td></tr>`); return `${pageHeader('AUDIT LOG', '操作日志', '记录上下架、核销和状态变更等关键操作。')}${adminTable(['时间', '操作者', '资源', '动作', '变更摘要'], rows)}`; }

  function renderServiceDetailCompact() { const service = store.getService(state.param); if (!service) return emptyState('服务不存在', '请返回享。'); const data = store.getState(); const merchant = store.getMerchant(service.merchantId); const availability = store.canPurchase(service.id); const reviews = data.reviews.filter(item => item.category === service.category); const comments = (data.comments || []).filter(item => item.serviceId === service.id); const bookingHint = service.category === '住宿' ? '预订时选择入住和离店日期' : service.category === '景区' ? '预订时选择入园日期和场次' : service.category === '餐饮' ? '团购支付后到店核销' : '下单时选择预约日期'; const image = service.image || merchant.image; return `${pageHeader(service.category, service.name, `${merchant.name} · ${merchant.address}`, '<button class="secondary-button" data-route="consume">返回“享”</button>')}<section class="compact-service-detail"><div class="compact-service-media">${image ? `<img src="${safe(image)}" alt="${safe(service.name)}" />` : `<span>${safe(service.symbol)}</span>`}</div><div class="compact-service-content"><div class="compact-service-price"><strong>${money(service.price)}</strong><span>${statusBadge(service.status)}</span></div><p class="compact-description">${safe(service.description)}</p><div class="compact-booking-hint"><b>${service.category === '餐饮' ? '核销方式' : '预订方式'}</b><span>${bookingHint}</span></div><div class="compact-tags">${(service.eventTags || []).slice(0, 3).map(tag => `<span>${safe(tag)}</span>`).join('')}</div></div></section><section class="section compact-reviews"><div class="section-heading"><h2>甄客帖</h2><button class="text-button" data-route="reviews">查看全部 →</button></div><div class="review-list">${reviews.slice(0, 2).map(reviewCard).join('') || emptyState('暂无甄客帖', '完成履约后可评价。')}</div></section><section class="section compact-comments"><div class="section-heading"><h2>评论区</h2><button class="text-button" data-demo-comment>我要提问</button></div><div class="comment-list">${comments.slice(0, 3).map(item => `<article class="comment-card"><strong>${safe(item.user)}</strong><p>${safe(item.text)}</p>${item.reply ? `<div><b>回复</b>${safe(item.reply)}</div>` : ''}</article>`).join('') || emptyState('暂无评论', '登录后可以提问。')}</div></section><div class="purchase-bar"><div><small>${merchant.name}</small><strong>${money(service.price)}</strong></div><button class="primary-button" ${availability.ok ? `data-buy="${service.id}"` : 'disabled'}>${availability.ok ? (service.category === '餐饮' ? '立即团购' : '立即预订') : availability.reason}</button></div>`; }

  function userById(id) { return (store.getState().users || []).find(item => item.id === id) || { id, nickname: '甄客用户', avatar: '甄', bio: '记录燃赛与城市' }; }
  function cityById(id) { return (store.getState().cities || []).find(item => item.id === id) || { id, name: id }; }
  function postCard(post) {
    const author = userById(post.authorId); const city = cityById(post.cityId);
    const liked = store.isPostLiked(post.id); const favorited = store.isPostFavorited(post.id);
    return `<article class="community-post-card"><button class="post-cover" data-route="post-detail" data-param="${post.id}"><img src="${safe(post.images?.[0] || 'assets/images/city-race.jpg')}" alt="${safe(post.title)}" loading="lazy" />${post.eventId ? '<span>燃赛真实分享</span>' : ''}</button><div class="post-copy"><div class="post-context"><button class="post-context-link" data-city-section="${post.cityId}|${safe(post.section)}">${safe(city.name)} · ${safe(post.section)}</button><span>${safe(post.createdAt)}</span></div><h3><button data-route="post-detail" data-param="${post.id}">${safe(post.title)}</button></h3><p>${safe(post.body)}</p><div class="post-tags">${(post.tags || []).map(tag => `<button class="topic-chip" data-route="topic" data-param="${safe(tag)}">#${safe(tag)}</button>`).join('')}</div><footer class="post-actions"><button class="author-link" data-route="author" data-param="${author.id}"><i>${avatarInner(author.avatar)}</i><span>${safe(author.nickname)}</span></button><div class="post-action-group"><button class="post-action ${liked ? 'is-active' : ''}" data-post-like="${post.id}"><span>${liked ? '♥' : '♡'}</span>${post.likeCount || 0}</button><button class="post-action ${favorited ? 'is-active' : ''}" data-post-favorite="${post.id}"><span>${favorited ? '★' : '☆'}</span>${post.favoriteCount || 0}</button><button class="post-action" data-route="post-detail" data-param="${post.id}"><span>💬</span>${post.commentCount || 0}</button></div></footer></div></article>`;
  }
  function renderRanHome() { const data = store.getState(); const event = data.events.find(item => item.status === 'PUBLISHED'); const groups = [['甄必吃', '餐饮', '比赛前后吃什么，本地人和跑友一起分享。'], ['甄必玩', '景区', '完赛后去哪走走，用真实体验认识定州。'], ['甄必住', '住宿', '只看位置、环境和跑友体验，不在这里预订。']]; const verifiedPosts = data.posts.filter(item => item.eventId || item.section === '旅游'); return `<section class="platform-home ran-home"><section class="event-home-card"><img src="assets/images/city-race.jpg" alt="燃赛定州赛事海报" /><div><span>燃赛定州 · ${safe(event.date)}</span><h1>${safe(event.title)}</h1><p>${safe(event.place)} · 跑进古城，把比赛变成一次城市旅行。</p><button class="primary-button" data-ransai>进入赛事专题</button></div></section><section class="verified-home-feed"><div class="section-heading"><div><h2>甄客帖</h2></div><button class="text-button" data-publish-post>发布 →</button></div><div class="home-story-track">${verifiedPosts.map(postCard).join('')}</div></section><section class="zhen-home-groups"><header><h2>甄必享</h2></header>${groups.map(([title, category, description]) => { const places = data.services.filter(item => item.category === category).slice(0, 2); return `<section class="zhen-home-section"><div class="zhen-home-heading"><div><h2>${title}</h2><p>${description}</p></div></div><div class="zhen-place-list">${places.map(serviceCard).join('')}</div></section>`; }).join('')}</section></section>`; }
  function renderEventsPlatform() { return renderRanHome(); }
  function renderDiscover() { const data = store.getState(); const posts = store.listPosts({ cityId: state.cityId, section: state.section }).filter(item => !state.query || JSON.stringify(item).includes(state.query)); return `<section class="community-page"><header class="community-header"><div><h1>天南海北燃赛人</h1></div><div class="community-header-actions"><button class="primary-button" data-publish-post>＋ 发布帖子</button></div></header><div class="community-shell"><nav class="section-tabs">${data.sections.map(item => `<button class="${item === state.section ? 'is-active' : ''}" data-section="${item}">${safe(item)}</button>`).join('')}</nav><div class="community-body"><aside class="city-rail">${data.cities.map(item => `<button class="city-rail-item ${item.id === state.cityId ? 'is-active' : ''}" data-city="${item.id}">${safe(item.name)}</button>`).join('')}</aside><div class="community-main"><div class="community-feed">${posts.length ? posts.map(postCard).join('') : emptyState('这里还没有帖子', '发布第一条真实的燃赛城市体验。')}</div></div></div></div><button class="publish-fab" data-publish-post aria-label="发布帖子">＋</button></section>`; }
  function commentNode(comment, isReply = false) {
    const commenter = userById(comment.authorId); const cliked = store.isPostCommentLiked(comment.id);
    const replies = comment.replies || [];
    const images = (comment.images || []).map(src => `<img class="comment-image" src="${safe(src)}" alt="评论图片" loading="lazy" />`).join('');
    const body = comment.body ? `<p class="comment-body">${renderCommentText(comment.body)}</p>` : '';
    return `<article class="post-comment ${isReply ? 'is-reply' : ''}"><button class="comment-avatar" data-route="author" data-param="${commenter.id}" aria-label="${safe(commenter.nickname)}">${avatarInner(commenter.avatar)}</button><div class="comment-main"><button class="comment-name" data-route="author" data-param="${commenter.id}">${safe(commenter.nickname)}</button>${body}${images ? `<div class="comment-images">${images}</div>` : ''}<div class="comment-foot"><small>${safe(comment.createdAt)}</small><button class="comment-reply-btn" data-reply-comment="${comment.id}" data-post-id="${comment.postId}">回复</button></div>${replies.length ? `<div class="comment-replies">${replies.map(reply => commentNode(reply, true)).join('')}</div>` : ''}</div><button class="comment-like ${cliked ? 'is-active' : ''}" data-comment-like="${comment.id}"><span>${cliked ? '♥' : '♡'}</span><b>${comment.likeCount || 0}</b></button></article>`;
  }
  // @提及高亮：把评论里的 @昵称 渲染成高亮片段。
  function renderCommentText(text) { return safe(text).replace(/@([^\s@]+)/g, '<span class="comment-mention">@$1</span>'); }
  function renderPostDetail() {
    const post = store.getState().posts.find(item => item.id === state.param); if (!post) return emptyState('帖子不存在', '返回“游”继续发现。');
    const author = userById(post.authorId); const city = cityById(post.cityId); const service = post.placeId ? store.getService(post.placeId) : null;
    const me = store.getState().currentUser; const isSelf = me && me.id === author.id;
    const following = store.isFollowing(author.id); const liked = store.isPostLiked(post.id); const favorited = store.isPostFavorited(post.id);
    const comments = store.listPostComments(post.id);
    return `<div class="pd-topbar"><button class="pd-back" data-route="consume" aria-label="返回">‹</button><button class="pd-author" data-route="author" data-param="${author.id}"><i>${avatarInner(author.avatar)}</i><b>${safe(author.nickname)}</b></button>${isSelf ? '' : `<button class="pd-follow ${following ? 'is-active' : ''}" data-follow="${author.id}">${following ? '已关注' : '关注'}</button>`}<button class="pd-share" data-share-post aria-label="分享">↗</button></div><article class="post-detail">${(post.images || []).map(image => `<img src="${safe(image)}" alt="${safe(post.title)}" />`).join('')}<div class="post-detail-copy">${post.title ? `<h1 class="pd-title">${safe(post.title)}</h1>` : ''}<p class="pd-body">${safe(post.body)}</p><div class="post-tags">${(post.tags || []).map(tag => `<button class="topic-chip" data-route="topic" data-param="${safe(tag)}">#${safe(tag)}</button>`).join('')}</div>${service ? (mch => { const dist = (2 + (service.id.charCodeAt(service.id.length - 1) % 90) / 10).toFixed(1); return `<button class="place-tag" data-map="${safe(mch?.address || service.name)}">📌 ${safe(service.name)} ${dist}km</button>`; })(store.getMerchant(service.merchantId)) : ''}<div class="pd-meta">${safe(city.name)} · ${safe(post.section)} · ${safe(post.createdAt)}</div></div></article><section class="section post-comment-section"><div class="comment-count-line">共 ${comments.length} 条评论</div><div class="post-comment-list">${comments.length ? comments.map(item => commentNode(item)).join('') : emptyState('还没有评论', '成为第一个和作者交流的人。')}</div></section><div class="comment-dock"><button class="comment-dock-input" data-comment-post="${post.id}">说点什么…</button><button class="comment-dock-icon ${liked ? 'is-active' : ''}" data-post-like="${post.id}"><span>${liked ? '♥' : '♡'}</span>${post.likeCount || 0}</button><button class="comment-dock-icon ${favorited ? 'is-active' : ''}" data-post-favorite="${post.id}"><span>${favorited ? '★' : '☆'}</span>${post.favoriteCount || 0}</button><button class="comment-dock-icon" data-comment-post="${post.id}"><span>💬</span>${post.commentCount || 0}</button></div>`;
  }
  function renderAuthor() { const author = userById(state.param); const posts = store.listPosts({ authorId: author.id }); const followers = (store.getState().follows || []).filter(item => item.followeeId === author.id).length; const isSelf = (store.getState().currentUser?.id || 'U001') === author.id; const following = store.isFollowing(author.id); return `<section class="author-profile"><i>${avatarInner(author.avatar)}</i><div><h1>${safe(author.nickname)}</h1><p>${safe(author.bio)}</p><span>${posts.length} 帖子 · ${followers} 粉丝 · ${posts.reduce((sum, item) => sum + (item.likeCount || 0), 0)} 获赞</span></div>${isSelf ? '' : `<button class="primary-button ${following ? 'is-active' : ''}" data-follow="${author.id}">${following ? '已关注' : '＋ 关注'}</button>`}</section><section class="section"><h2>TA 的燃赛与城市故事</h2><div class="community-feed">${posts.length ? posts.map(postCard).join('') : emptyState('还没有公开帖子', '关注 TA，第一时间看到新分享。')}</div></section>`; }
  function renderProfilePlatform() {
    const data = store.getState(); const me = userById('U001');
    if (!data.currentUser) { return `<section class="profile-community"><header class="profile-hero-card profile-guest"><button class="profile-hero-avatar" data-route="login" aria-label="登录">甄</button><div class="profile-hero-copy"><h1>登录 / 注册</h1><p>登录后可发布、关注、点赞和收藏</p></div><button class="primary-button" data-route="login">去登录</button></header><section class="profile-entries"><button class="profile-mall-entry" data-route="mall"><span class="profile-cell-icon mall">商</span><div><b>商城订单</b><small>社区内容与商城订单分开管理</small></div><span class="profile-mall-arrow">›</span></button></section></section>`; }
    const mine = store.listPosts({ authorId: 'U001' });
    const following = (data.follows || []).filter(item => item.followerId === 'U001').length;
    const followers = (data.follows || []).filter(item => item.followeeId === 'U001').length;
    const likes = mine.reduce((sum, item) => sum + (item.likeCount || 0), 0);
    const favorites = store.listFavoritePosts().length;
    const interactions = store.listReceivedInteractions().length;
    const stats = [[mine.length, '帖子'], [following, '关注'], [followers, '粉丝'], [likes, '获赞']];
    const entries = [
      ['my-favorites', '藏', '我的收藏', `${favorites} 条收藏`],
      ['my-interactions', '讯', '消息', `${interactions} 条新消息`],
      ['mall', '商', '商城订单', '社区内容与商城订单分开管理']
    ];
    return `<section class="profile-community"><header class="profile-hero-card"><div class="profile-hero-top"><button class="profile-hero-avatar" data-change-avatar aria-label="更换头像">${avatarInner(me.avatar)}</button><div class="profile-hero-copy"><h1>${safe(me.nickname)}</h1><p>${safe(me.bio)}</p></div><button class="profile-edit-btn" data-route="profile-settings" aria-label="编辑资料">✎</button></div><div class="profile-stats">${stats.map(([value, label]) => `<div class="profile-stat"><b>${value}</b><span>${label}</span></div>`).join('')}</div></header><section class="profile-entries">${entries.map(([route, icon, title, desc]) => `<button class="profile-mall-entry" data-route="${route}"><span class="profile-cell-icon${route === 'mall' ? ' mall' : ''}">${icon}</span><div><b>${title}</b><small>${desc}</small></div><span class="profile-mall-arrow">›</span></button>`).join('')}</section></section>`;
  }
  function authorRow(user) { const following = store.isFollowing(user.id); const isSelf = (store.getState().currentUser?.id || 'U001') === user.id; const posts = store.listPosts({ authorId: user.id }); return `<article class="author-list-item"><button class="author-row" data-route="author" data-param="${user.id}"><i>${avatarInner(user.avatar)}</i><span><b>${safe(user.nickname)}</b><small>${safe(user.bio)}</small></span></button>${isSelf ? '' : `<button class="secondary-button small-button ${following ? 'is-active' : ''}" data-follow="${user.id}">${following ? '已关注' : '＋ 关注'}</button>`}<span class="author-post-count">${posts.length} 帖</span></article>`; }
  function socialBackHeader(kicker, title, description) { return pageHeader(kicker, title, description, '<button class="secondary-button" data-route="profile">返回我的</button>'); }
  function renderMyPosts() { if (!requireLogin('查看我的帖子')) return ''; const posts = store.listPosts({ authorId: 'U001' }); return `${socialBackHeader('MY POSTS', '我的帖子')}<div class="community-feed">${posts.length ? posts.map(postCard).join('') : emptyState('还没有发布帖子', '去“游”发布第一条分享。')}</div>`; }
  function renderMyFavorites() { if (!requireLogin('查看我的收藏')) return ''; const posts = store.listFavoritePosts(); return `${socialBackHeader('MY FAVORITES', '我的收藏')}<div class="community-feed">${posts.length ? posts.map(postCard).join('') : emptyState('还没有收藏', '在帖子里点收藏，方便以后回看。')}</div>`; }
  function renderMyLikes() { if (!requireLogin('查看我的点赞')) return ''; const posts = store.listLikedPosts(); return `${socialBackHeader('MY LIKES', '我的点赞')}<div class="community-feed">${posts.length ? posts.map(postCard).join('') : emptyState('还没有点赞', '喜欢的帖子点个赞吧。')}</div>`; }
  function renderMyFollowing() { if (!requireLogin('查看我的关注')) return ''; const users = store.listFollowing(); return `${socialBackHeader('MY FOLLOWING', '我的关注')}<div class="author-list">${users.length ? users.map(authorRow).join('') : emptyState('还没有关注任何人', '在帖子或作者主页关注感兴趣的跑友。')}</div>`; }
  function renderMyFollowers() { if (!requireLogin('查看我的粉丝')) return ''; const users = store.listFollowers(); return `${socialBackHeader('MY FOLLOWERS', '我的粉丝')}<div class="author-list">${users.length ? users.map(authorRow).join('') : emptyState('还没有粉丝', '持续分享，会有更多人关注你。')}</div>`; }
  function renderMyInteractions() {
    if (!requireLogin('查看消息')) return '';
    const items = store.listReceivedInteractions();
    const label = { comment: '评论了你的帖子', like: '点赞了你的帖子', favorite: '收藏了你的帖子', follow: '关注了你' };
    return `${socialBackHeader('MESSAGES', '消息')}<div class="interaction-list">${items.length ? items.map(item => { const user = userById(item.userId); const post = item.postId ? store.getState().posts.find(post => post.id === item.postId) : null; return `<article class="interaction-item"><button class="author-link" data-route="author" data-param="${user.id}"><i>${avatarInner(user.avatar)}</i>${safe(user.nickname)}</button><span>${label[item.type]}</span>${item.body ? `<p>${safe(item.body)}</p>` : ''}${post ? `<button class="text-button" data-route="post-detail" data-param="${post.id}">查看《${safe(post.title)}》 →</button>` : ''}</article>`; }).join('') : emptyState('还没有新消息', '发布真实内容，互动会陆续到来。')}</div>`;
  }
  function startPublish(placeId = '') {
    const place = placeId ? store.getService(placeId) : null;
    state.publishDraft = { step: 'album', images: [], placeId: placeId || '', placeName: place ? place.name : '', title: '', body: '', topics: [], cityId: state.cityId, section: state.route === 'events' ? '旅游' : state.section, eventId: state.route === 'events' ? 'E001' : null };
    go('publish');
  }
  const commentEmojis = ['😀', '😂', '🥲', '😍', '👍', '🙏', '🔥', '💪', '🏃', '🎉', '❤️', '👏', '😭', '🤙', '✨', '🥳'];
  // 小红书式评论输入：文字 + 表情 + 图片 + @用户。draft 挂在弹层上，随交互更新。
  function openCommentComposer(postId, parentId, replyToName) {
    if (!requireLogin(parentId ? '回复评论' : '发布评论')) return;
    const composer = { images: [] };
    const mentionUsers = (store.getState().users || []).filter(user => user.id !== (store.getState().currentUser?.id || 'U001'));
    const body = `<div class="comment-composer">
      <textarea data-composer-text maxlength="200" placeholder="${replyToName ? `回复 @${safe(replyToName)}：` : '写下你的真实体验、和跑友聊聊…'}">${replyToName ? `@${replyToName} ` : ''}</textarea>
      <div class="composer-thumbs" data-composer-thumbs hidden></div>
      <div class="composer-tools">
        <button type="button" class="composer-tool" data-composer-toggle="emoji" aria-label="表情">☺</button>
        <button type="button" class="composer-tool" data-composer-toggle="image" aria-label="图片">🖼</button>
        <button type="button" class="composer-tool" data-composer-toggle="mention" aria-label="提及用户">@</button>
      </div>
      <div class="composer-panel" data-composer-panel="emoji" hidden><div class="emoji-grid">${commentEmojis.map(emoji => `<button type="button" class="emoji-btn" data-emoji="${emoji}">${emoji}</button>`).join('')}</div></div>
      <div class="composer-panel" data-composer-panel="image" hidden><div class="composer-album">${albumPhotos.map(photo => `<button type="button" class="composer-album-cell" data-composer-image="${safe(photo.src)}"><img src="${safe(photo.src)}" alt="${safe(photo.label)}" /></button>`).join('')}</div></div>
      <div class="composer-panel" data-composer-panel="mention" hidden><div class="mention-list">${mentionUsers.map(user => `<button type="button" class="mention-item" data-mention="${safe(user.nickname)}"><i>${avatarInner(user.avatar)}</i>${safe(user.nickname)}</button>`).join('')}</div></div>
    </div>`;
    openDialog({ kicker: parentId ? '追评' : '真实交流', title: parentId ? '回复评论' : '写评论', body, confirmText: '发布', onConfirm: () => {
      const text = (dialogContent.querySelector('[data-composer-text]')?.value || '').trim();
      try { store.addPostComment(postId, text, { parentId, images: composer.images }); showToast(parentId ? '回复已发布' : '评论已发布'); render(); }
      catch (error) { showToast(error.message); }
    } });
    // 弹层内交互（表情插入、图片选择、@用户、面板切换）
    dialogContent.querySelector('.comment-composer')?.addEventListener('click', event => {
      const toggle = event.target.closest('[data-composer-toggle]');
      if (toggle) { const key = toggle.dataset.composerToggle; dialogContent.querySelectorAll('[data-composer-panel]').forEach(panel => { panel.hidden = panel.dataset.composerPanel === key ? !panel.hidden : true; }); dialogContent.querySelectorAll('[data-composer-toggle]').forEach(btn => btn.classList.toggle('is-active', btn === toggle && !dialogContent.querySelector(`[data-composer-panel="${key}"]`).hidden)); return; }
      const emoji = event.target.closest('[data-emoji]');
      if (emoji) { insertAtCursor(dialogContent.querySelector('[data-composer-text]'), emoji.dataset.emoji); return; }
      const mention = event.target.closest('[data-mention]');
      if (mention) { insertAtCursor(dialogContent.querySelector('[data-composer-text]'), `@${mention.dataset.mention} `); return; }
      const image = event.target.closest('[data-composer-image]');
      if (image) { const src = image.dataset.composerImage; const index = composer.images.indexOf(src); if (index >= 0) composer.images.splice(index, 1); else { if (composer.images.length >= 9) { showToast('最多 9 张图片'); return; } composer.images.push(src); } image.classList.toggle('is-selected'); refreshComposerThumbs(composer.images); return; }
    });
  }
  function insertAtCursor(textarea, text) { if (!textarea) return; const start = textarea.selectionStart ?? textarea.value.length; const end = textarea.selectionEnd ?? textarea.value.length; textarea.value = textarea.value.slice(0, start) + text + textarea.value.slice(end); const pos = start + text.length; textarea.focus(); textarea.setSelectionRange(pos, pos); }
  function refreshComposerThumbs(images) { const box = dialogContent.querySelector('[data-composer-thumbs]'); if (!box) return; box.hidden = !images.length; box.innerHTML = images.map(src => `<img src="${src}" alt="已选图片" />`).join(''); }
  function savePublishFormFields() {
    const form = main.querySelector('[data-publish-form]'); if (!form || !state.publishDraft) return;
    const data = new FormData(form);
    state.publishDraft.title = data.get('title') ?? state.publishDraft.title;
    state.publishDraft.body = data.get('body') ?? state.publishDraft.body;
    if (data.get('cityId')) state.publishDraft.cityId = data.get('cityId');
    if (data.get('section')) state.publishDraft.section = data.get('section');
  }
  function renderPublish() {
    const draft = state.publishDraft;
    if (!draft) { return emptyState('没有进行中的发布', '返回“游”重新点击发布。'); }
    if (draft.step === 'album') {
      const selected = draft.images;
      return `<section class="publish-flow publish-album"><header class="publish-topbar"><button class="publish-cancel" data-publish-cancel>取消</button><b>选择图片</b><button class="publish-next ${selected.length ? '' : 'is-disabled'}" ${selected.length ? 'data-publish-to-edit' : 'disabled'}>下一步${selected.length ? ` (${selected.length})` : ''}</button></header><p class="publish-album-hint">从相册选择 1–9 张图片</p><div class="album-grid">${albumPhotos.map(photo => { const index = selected.indexOf(photo.src); const on = index >= 0; return `<button class="album-cell ${on ? 'is-selected' : ''}" data-album-pick="${photo.src}"><img src="${safe(photo.src)}" alt="${safe(photo.label)}" loading="lazy" /><span class="album-badge">${on ? index + 1 : ''}</span><small>${safe(photo.label)}</small></button>`; }).join('')}</div></section>`;
    }
    const places = publishPlaces();
    return `<section class="publish-flow publish-edit"><header class="publish-topbar"><button class="publish-cancel" data-publish-back-album>‹ 返回</button><b>编辑帖子</b><button class="publish-next" data-publish-submit>发布</button></header><form class="publish-edit-form" data-publish-form><div class="publish-thumbs">${draft.images.map((src, index) => `<div class="publish-thumb"><img src="${safe(src)}" alt="已选图片 ${index + 1}" /><button type="button" class="publish-thumb-remove" data-publish-remove="${safe(src)}" aria-label="移除">×</button></div>`).join('')}<button type="button" class="publish-thumb-add" data-publish-back-album aria-label="继续添加图片">＋</button></div><input class="publish-title" name="title" maxlength="30" placeholder="添加标题" value="${safe(draft.title)}" /><textarea class="publish-body" name="body" maxlength="1000" placeholder="添加正文，写下你的真实参赛、到访和城市体验…">${safe(draft.body)}</textarea><div class="publish-fields"><button type="button" class="publish-field" data-publish-place><span class="publish-field-icon">◎</span><b>${draft.placeName ? safe(draft.placeName) : '标记地点'}</b><span class="publish-field-arrow">›</span></button><label class="publish-field"><span class="publish-field-icon">城</span><select name="cityId">${(store.getState().cities || []).map(city => `<option value="${city.id}" ${draft.cityId === city.id ? 'selected' : ''}>${safe(city.name)}</option>`).join('')}</select></label><label class="publish-field"><span class="publish-field-icon">区</span><select name="section">${(store.getState().sections || []).map(section => `<option ${draft.section === section ? 'selected' : ''}>${safe(section)}</option>`).join('')}</select></label></div><div class="publish-topics"><div class="publish-topics-title"><span class="publish-field-icon">#</span>选择话题 <small>最多 3 个（${draft.topics.length}/3）</small></div><div class="publish-topic-chips">${presetTopics.map(topic => { const on = draft.topics.includes(topic); return `<button type="button" class="publish-topic-chip ${on ? 'is-active' : ''}" data-publish-topic="${safe(topic)}">#${safe(topic)}</button>`; }).join('')}</div></div></form></section>`;
  }
  function renderTopic() {
    const tag = state.param; const posts = store.listPosts({ tag });
    return `${pageHeader('', `#${tag}`, `${posts.length} 条相关分享`, '<button class="secondary-button" data-route="consume">返回“游”</button>')}<div class="community-feed">${posts.length ? posts.map(postCard).join('') : emptyState('这个话题还没有帖子', '发布第一条带这个话题的分享。')}</div>`;
  }
  function renderContentDetail() { const service = store.getService(state.param); if (!service) return emptyState('地点不存在', '请返回“游”。'); const merchant = store.getMerchant(service.merchantId); const posts = store.getState().posts.filter(item => item.placeId === service.id); return `${pageHeader('', service.name, `${merchant.name} · ${merchant.address}`)}<section class="content-detail"><img src="${safe(service.image || 'assets/images/ancient-city.jpg')}" alt="${safe(service.name)}" /><div class="content-detail-body"><p>${safe(service.description)}</p><button class="content-detail-info content-detail-map" data-map="${safe(merchant.address)}"><span>地址</span><b>${safe(merchant.address)} ›</b></button><div class="content-detail-info"><span>营业 / 开放</span><b>${safe(merchant.hours)}</b></div><div class="content-detail-info"><span>电话</span><b>${safe(merchant.phone)}</b></div><button class="primary-button content-detail-publish" data-publish-post data-place-id="${service.id}">发布甄客帖</button></div></section><section class="section"><div class="section-heading"><div><h2>甄客帖</h2><p>${posts.length} 条真实分享</p></div></div><div class="community-feed">${posts.length ? posts.map(postCard).join('') : emptyState('还没有帖子', '成为第一个分享这里的人。')}</div></section>`; }

  const views = { home: renderRanHome, events: renderEventsPlatform, 'event-detail': renderEventDetail, consume: renderDiscover, mall: renderMall, 'post-detail': renderPostDetail, author: renderAuthor, 'my-posts': renderMyPosts, 'my-favorites': renderMyFavorites, 'my-likes': renderMyLikes, 'my-following': renderMyFollowing, 'my-followers': renderMyFollowers, 'my-interactions': renderMyInteractions, 'profile-settings': renderProfileSettings, publish: renderPublish, topic: renderTopic, category: renderCategory, 'merchant-detail': renderMerchantDetail, 'service-detail': renderContentDetail, login: renderLogin, profile: renderProfilePlatform, 'admin-login': renderAdminLogin, 'admin-dashboard': renderAdminDashboard, 'admin-merchants': renderAdminMerchants, 'admin-services': renderAdminServices, 'admin-content': renderAdminContent, 'admin-region': renderAdminRegion, 'admin-audit': renderAdminAudit };
  function render() { renderShell(); main.innerHTML = (views[state.route] || renderHome)(); main.focus({ preventScroll: true }); window.scrollTo({ top: 0, behavior: 'instant' }); }

  document.addEventListener('click', event => {
    const routeButton = event.target.closest('[data-route]'); if (routeButton) { go(routeButton.dataset.route, routeButton.dataset.param || ''); return; }
    const cityButton = event.target.closest('[data-city]'); if (cityButton) { state.cityId = cityButton.dataset.city; render(); return; }
    const sectionButton = event.target.closest('[data-section]'); if (sectionButton) { state.section = sectionButton.dataset.section; render(); return; }
    const citySection = event.target.closest('[data-city-section]'); if (citySection) { const [cityId, section] = citySection.dataset.citySection.split('|'); state.cityId = cityId; state.section = section; go('consume'); return; }
    const followButton = event.target.closest('[data-follow]'); if (followButton) { if (!requireLogin('关注作者')) return; try { const result = store.toggleFollow(followButton.dataset.follow); showToast(result.following ? '已关注，可在“我的关注”查看' : '已取消关注'); render(); } catch (error) { showToast(error.message); } return; }
    const postLike = event.target.closest('[data-post-like]'); if (postLike) { if (!requireLogin('点赞')) return; store.togglePostLike(postLike.dataset.postLike); render(); return; }
    const postFavorite = event.target.closest('[data-post-favorite]'); if (postFavorite) { if (!requireLogin('收藏')) return; store.togglePostFavorite(postFavorite.dataset.postFavorite); showToast('收藏状态已更新'); render(); return; }
    const serviceLike = event.target.closest('[data-service-like]'); if (serviceLike) { if (!requireLogin('点赞')) return; store.toggleServiceLike(serviceLike.dataset.serviceLike); render(); return; }
    const serviceFavorite = event.target.closest('[data-service-favorite]'); if (serviceFavorite) { if (!requireLogin('收藏')) return; store.toggleServiceFavorite(serviceFavorite.dataset.serviceFavorite); showToast('收藏状态已更新'); render(); return; }
    if (event.target.closest('[data-share-post]')) { showToast('分享链接已复制（模拟）'); return; }
    const mapButton = event.target.closest('[data-map]'); if (mapButton) { window.open(`https://uri.amap.com/search?keyword=${encodeURIComponent(mapButton.dataset.map)}`, '_blank', 'noopener'); return; }
    const commentLike = event.target.closest('[data-comment-like]'); if (commentLike) { if (!requireLogin('点赞评论')) return; try { store.togglePostCommentLike(commentLike.dataset.commentLike); render(); } catch (error) { showToast(error.message); } return; }
    const replyComment = event.target.closest('[data-reply-comment]'); if (replyComment) { const parent = store.getState().postComments.find(item => item.id === replyComment.dataset.replyComment); const replyToName = parent ? userById(parent.authorId).nickname : ''; openCommentComposer(replyComment.dataset.postId, replyComment.dataset.replyComment, replyToName); return; }
    const commentPost = event.target.closest('[data-comment-post]'); if (commentPost) { openCommentComposer(commentPost.dataset.commentPost, null, ''); return; }
    const buy = event.target.closest('[data-buy]'); if (buy) { state.pendingServiceId = buy.dataset.buy; state.returnAfterLogin = `checkout/${buy.dataset.buy}`; go(store.getState().currentUser ? 'checkout' : 'login', buy.dataset.buy); return; }
    const pay = event.target.closest('[data-pay]'); if (pay) { const order = store.applyPaymentResult(state.param, pay.dataset.pay); go('payment-result', order.id); return; }
    const like = event.target.closest('[data-like]'); if (like) { const review = store.likeReview(like.dataset.like); like.textContent = `♥ 有用 ${review.likes}`; showToast('已标记为有用（模拟）'); return; }
    const orderFilter = event.target.closest('[data-order-filter]'); if (orderFilter) { state.orderFilter = orderFilter.dataset.orderFilter; render(); return; }
    const reviewFilter = event.target.closest('[data-review-filter]'); if (reviewFilter) { state.reviewCategory = reviewFilter.dataset.reviewFilter; render(); return; }
    const commentButton = event.target.closest('[data-demo-comment]'); if (commentButton) { if (!store.getState().currentUser) { state.returnAfterLogin = `service-detail/${state.param}`; go('login', state.param); return; } openDialog({ kicker: '评论区', title: '我要提问', body: `<form data-comment-form><label>内容<textarea name="text" required maxlength="200" placeholder="写下你的问题或体验交流"></textarea></label></form>`, confirmText: '发布评论', onConfirm: () => { const form = dialogContent.querySelector('[data-comment-form]'); const text = new FormData(form).get('text'); try { store.addComment({ serviceId: state.param, user: store.getState().currentUser.name, text }); showToast('评论已发布'); render(); } catch (error) { showToast(error.message); } } }); return; }
    const publishButton = event.target.closest('[data-publish-post]'); if (publishButton) { if (!requireLogin('发布帖子')) return; startPublish(publishButton.dataset.placeId || ''); return; }
    const albumPick = event.target.closest('[data-album-pick]'); if (albumPick && state.publishDraft) { const src = albumPick.dataset.albumPick; const images = state.publishDraft.images; const index = images.indexOf(src); if (index >= 0) images.splice(index, 1); else { if (images.length >= 9) { showToast('最多选择 9 张图片'); return; } images.push(src); } render(); return; }
    if (event.target.closest('[data-publish-to-edit]') && state.publishDraft) { if (!state.publishDraft.images.length) { showToast('请至少选择一张图片'); return; } state.publishDraft.step = 'edit'; render(); return; }
    if (event.target.closest('[data-publish-back-album]') && state.publishDraft) { savePublishFormFields(); state.publishDraft.step = 'album'; render(); return; }
    const publishRemove = event.target.closest('[data-publish-remove]'); if (publishRemove && state.publishDraft) { savePublishFormFields(); const src = publishRemove.dataset.publishRemove; state.publishDraft.images = state.publishDraft.images.filter(item => item !== src); render(); return; }
    if (event.target.closest('[data-publish-cancel]')) { state.publishDraft = null; go(state.returnAfterLogin || 'consume'); state.returnAfterLogin = ''; return; }
    if (event.target.closest('[data-publish-place]') && state.publishDraft) { savePublishFormFields(); const places = publishPlaces(); openDialog({ kicker: '标记地点', title: '选择关联地点', body: `<div class="place-options">${['<button type="button" class="place-option" data-place-choice="">不标记地点</button>', ...places.map(place => `<button type="button" class="place-option" data-place-choice="${place.id}" data-place-name="${safe(place.name)}">${safe(place.name)}</button>`)].join('')}</div>`, confirmText: '完成', onConfirm: () => render() }); return; }
    const placeChoice = event.target.closest('[data-place-choice]'); if (placeChoice && state.publishDraft) { state.publishDraft.placeId = placeChoice.dataset.placeChoice || ''; state.publishDraft.placeName = placeChoice.dataset.placeName || ''; document.querySelectorAll('[data-place-choice]').forEach(item => item.classList.toggle('is-selected', item === placeChoice)); return; }
    const topicChip = event.target.closest('[data-publish-topic]'); if (topicChip && state.publishDraft) { savePublishFormFields(); const topic = topicChip.dataset.publishTopic; const topics = state.publishDraft.topics; const index = topics.indexOf(topic); if (index >= 0) topics.splice(index, 1); else { if (topics.length >= 3) { showToast('最多选择 3 个话题'); return; } topics.push(topic); } render(); return; }
    if (event.target.closest('[data-publish-submit]') && state.publishDraft) { savePublishFormFields(); const draft = state.publishDraft; try { const post = store.addPost({ cityId: draft.cityId, section: draft.section, title: draft.title, text: draft.body, images: draft.images, tags: draft.topics, placeId: draft.placeId, eventId: draft.eventId }); state.cityId = post.cityId; state.section = post.section; state.publishDraft = null; showToast('帖子已发布到对应城市与分区'); go('post-detail', post.id); } catch (error) { showToast(error.message); } return; }
    const avatarButton = event.target.closest('[data-change-avatar]'); if (avatarButton) { if (!store.getState().currentUser) { go('login'); return; } const current = userById('U001').avatar; openDialog({ kicker: '个人资料', title: '从相册选择头像', body: `<div class="avatar-album">${albumPhotos.map(photo => `<button type="button" class="avatar-album-cell ${current === photo.src ? 'is-selected' : ''}" data-avatar="${safe(photo.src)}"><img src="${safe(photo.src)}" alt="${safe(photo.label)}" /></button>`).join('')}</div>`, confirmText: '完成', onConfirm: () => { showToast('头像已更新'); render(); } }); return; }
    const avatarOption = event.target.closest('[data-avatar]'); if (avatarOption) { store.updateUserAvatar(avatarOption.dataset.avatar); document.querySelectorAll('[data-avatar]').forEach(item => item.classList.toggle('is-selected', item === avatarOption)); return; }
    const regionSwitch = event.target.closest('[data-region-switch]'); if (regionSwitch) { openDialog({ kicker: '地区', title: '切换地区', body: '<div class="region-options"><button type="button" data-region="定州">定州</button><button type="button" data-region="保定">保定</button><button type="button" data-region="石家庄">石家庄</button></div>', confirmText: '完成', onConfirm: () => { showToast(`已切换至${state.regionName}`); render(); } }); return; }
    const regionOption = event.target.closest('[data-region]'); if (regionOption) { state.regionName = regionOption.dataset.region; document.querySelectorAll('[data-region]').forEach(item => item.classList.toggle('is-selected', item === regionOption)); return; }
    const sendCode = event.target.closest('[data-send-code]'); if (sendCode) { if (sendCode.disabled) return; const phoneInput = sendCode.closest('form')?.querySelector('[name="phone"]'); if (!/^1[0-9]{10}$/.test(phoneInput?.value || '')) { showToast('请先输入正确的手机号'); phoneInput?.focus(); return; } showToast('验证码已发送（演示环境请输入任意 6 位数字）'); let left = 60; sendCode.disabled = true; sendCode.textContent = `${left}s 后重试`; clearInterval(sendCode.timer); sendCode.timer = setInterval(() => { left -= 1; if (left <= 0) { clearInterval(sendCode.timer); sendCode.disabled = false; sendCode.textContent = '获取验证码'; } else sendCode.textContent = `${left}s 后重试`; }, 1000); return; }
    if (event.target.closest('[data-logout]')) { openDialog({ kicker: '账号', title: '退出登录', body: '<p>退出后需要重新登录才能发布和互动。</p>', confirmText: '退出登录', onConfirm: () => { store.logout(); showToast('已退出登录'); go('profile'); } }); return; }
    if (event.target.closest('[data-ransai]')) { showToast('暂未开放燃赛链接'); return; }
    if (event.target.closest('[data-reset]')) { openDialog({ title: '重置演示数据', body: '<p>将恢复全部初始模拟数据，包括订单、上下架状态和日志。</p>', confirmText: '确认重置', onConfirm: () => { store.reset(); showToast('演示数据已重置'); render(); } }); return; }
    const merchantToggle = event.target.closest('[data-toggle-merchant]'); if (merchantToggle) { const merchant = store.getMerchant(merchantToggle.dataset.toggleMerchant); store.updateMerchantStatus(merchant.id, merchant.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE', state.admin.id); showToast('商家状态已更新'); render(); return; }
    const serviceToggle = event.target.closest('[data-toggle-service]'); if (serviceToggle) { const service = store.getService(serviceToggle.dataset.toggleService); store.updateServiceStatus(service.id, service.status === 'ON_SALE' ? 'OFF_SALE' : 'ON_SALE', state.admin.id); showToast('服务状态已更新'); render(); return; }
    const contentToggle = event.target.closest('[data-toggle-content]'); if (contentToggle) { const content = store.getState().contents.find(item => item.id === contentToggle.dataset.toggleContent); store.updateContentStatus(content.id, content.status === 'PUBLISHED' ? 'DRAFT' : 'PUBLISHED', state.admin.id); showToast('内容状态已更新'); render(); return; }
    const adminAction = event.target.closest('[data-admin-order-action]'); if (adminAction) { const id = adminAction.dataset.id; const action = adminAction.dataset.adminOrderAction; if (action === 'VERIFY') store.verifyOrder(id, state.admin.id); else store.updateOrderStatus(id, action === 'CONFIRM' ? 'CONFIRMED' : 'REFUNDED', state.admin.id); showToast('订单状态已更新'); render(); return; }
    if (event.target.closest('[data-demo-add], [data-demo-edit]')) { showToast('第一轮展示管理入口，具体字段待真实数据确认'); return; }
    if (event.target.closest('[data-close-dialog]')) closeDialog();
  }, true);
  document.addEventListener('submit', event => {
    event.preventDefault();
    const form = event.target;
    if (form.matches('[data-user-login]')) { const data = new FormData(form); const phone = String(data.get('phone') || ''); const code = String(data.get('code') || ''); if (!/^1[0-9]{10}$/.test(phone)) { showToast('请输入正确的手机号'); return; } if (!/^[0-9]{6}$/.test(code)) { showToast('请输入 6 位验证码'); return; } store.loginUser(phone); const target = state.returnAfterLogin || (state.pendingServiceId ? `checkout/${state.pendingServiceId}` : 'profile'); state.returnAfterLogin = ''; location.hash = target; showToast('登录成功'); return; }
    if (form.matches('[data-checkout]')) { const data = new FormData(form); const service = store.getService(form.dataset.serviceId); try { const order = store.createOrder({ userId: store.getState().currentUser.id, serviceId: form.dataset.serviceId, quantity: data.get('quantity'), contactName: data.get('guestName') || data.get('contactName') || '甄客用户', contactPhone: data.get('contactPhone'), guestName: data.get('guestName'), useDate: data.get('checkInDate') || data.get('visitDate') || data.get('useDate'), endDate: data.get('checkOutDate'), useTime: data.get('useTime'), visitSlot: data.get('visitSlot'), bookingType: service.category, note: data.get('note') }); go('payment', order.id); } catch (error) { showToast(error.message); } return; }
    if (form.matches('[data-profile-settings]')) { const data = new FormData(form); store.updateUserProfile({ name: data.get('name'), bio: data.get('bio') }); showToast('资料已保存'); go('profile'); return; }
    if (form.matches('[data-admin-login]')) { const data = new FormData(form); state.admin = store.loginAdmin(data.get('account')); if (state.admin) { window.sessionStorage.setItem('zhenkexing-admin-id', state.admin.id); go('admin-dashboard'); showToast('已进入运营管理员模拟后台'); } else showToast('演示账号不存在'); }
  }, true);
  document.addEventListener('input', event => { if (event.target.matches('[data-search]')) { state.query = event.target.value.trim(); clearTimeout(state.searchTimer); state.searchTimer = setTimeout(() => { if (state.route === 'home' && state.query) go('consume'); else render(); }, 120); } }, true);
  dialogConfirm.addEventListener('click', () => { const action = state.dialogAction; closeDialog(); if (action) action(); });
  window.addEventListener('hashchange', () => { parseHash(); render(); });
  parseHash(); render();
})();
